debug

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -31,5 +31,7 @@ jobs:
           cache: 'yarn'
       - run: yarn install
       - name: yarn prettier
-        run: |
-          yarn prettier || echo "::error ::Run yarn prettier:fix"
+      - run: |
+          if ! yarn prettier; then
+            exit $? && echo "::error ::Run yarn prettier:fix"
+          fi
