Warn user to run yarn prettier:fix if prettier job fails (#118)
* Test notice, error, and warning on workflow

* prettier:fix

* if (failure)

* Fix if condition in lint workflow

* prettier:fix

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,7 +17,7 @@ jobs:
         with:
           node-version: latest
           cache: 'yarn'
-      - run: yarn install --immutable
+      - run: yarn install
       - run: yarn lint
 
   prettier:
@@ -29,5 +29,9 @@ jobs:
         with:
           node-version: latest
           cache: 'yarn'
-      - run: yarn install --immutable
-      - run: yarn prettier
+      - run: yarn install
+      - name: Run yarn prettier
+        run: |
+          if ! yarn prettier; then
+            echo "::error ::Style issues found, run 'yarn prettier:fix'" && exit 1
+          fi
