debug

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -30,10 +30,11 @@ jobs:
           node-version: latest
           cache: 'yarn'
       - run: yarn install
-      - name: Run yarn prettier
-        run: |
-          if ! yarn prettier; then
-            echo "::error ::Run yarn prettier:fix" && exit 1
-          fi
-      - if: ${{ failure() }}
+      # - name: Run yarn prettier
+        # run: |
+        #   if ! yarn prettier; then
+        #     echo "::error ::Run yarn prettier:fix" && exit 1
+        #   fi
+      - run: yarn prettier
+        if: ${{ failure() }}
         run: echo "::error ::Run yarn prettier"
